### ISSUE TITLE
print() is a function in Python 3

### ISSUE THREAD

**Issue by cclauss** [albertpumarola/GANimation#1]
Also __async__ is a reserved word in Python 3.7+... https://github.com/pytorch/pytorch/pull/4999

flake8 testing of https://github.com/albertpumarola/GANimation on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./networks/networks.py:20:38: E999 SyntaxError: invalid syntax
        print "Network %s was created" % network_name
                                     ^
./models/ganimation.py:106:84: E999 SyntaxError: invalid syntax
            self._input_real_img = self._input_real_img.cuda(self._gpu_ids[0], async=True)
                                                                                   ^
./models/models.py:91:40: E999 SyntaxError: invalid syntax
            print 'loaded optimizer: %s' % load_path
                                       ^
./data/dataset_aus.py:37:63: E999 SyntaxError: invalid syntax
                print 'error reading image %s, skipping sample' % sample_id
                                                              ^
4     E999 SyntaxError: invalid syntax
4
```

**Comment by albertpumarola** [comment]
Code was developed for Python 2.7

**Comment by yangzhikai** [comment]
I used 2to3.py to transform , and have some error .Did you try this way?@cclauss

**Comment by cclauss** [comment]
2to3 is not advised because often it breaks Python 2 compatibility to achieve Python 3 compatibility.

I would recommend the use of futurize or modernize if you want compatibility with BOTH.
