### ISSUE TITLE
would you share me a trained model

### ISSUE THREAD

**Issue by hfengzhi** [albertpumarola/GANimation#11]
Thank you for sharing your code. But I meet an error when I run test.py. The error is like this:
_load_path), 'Weights file not found. Have you trained a model!? We are not providing one' % load_path_
And I just see that the folder have no .pth files.  Would you please share me a trained  model. Thank you!

**Comment by albertpumarola** [comment]
Hi,
For the moment we are not planning to release the trained model as we are working on future improvements. Everything is prepared to be easily trained with any dataset containing faces. The readme contains all the instructions.
