### ISSUE TITLE
some odd bugs abuout my test

### ISSUE THREAD

**Issue by vimalkashore** [albertpumarola/GANimation#14]
dear friend:
thank you for sharing your code,however when i "import torchvision.transforms as transforms" and "from utils import face_utils",there was a "Segmentation fault (core dumped)".when i run only one of them it 's fine.i seems that there is a  conflict .Would you mind take some suggest.

**Comment by albertpumarola** [comment]
It looks like you have some problem with the libraries verisons... I haven't been able to replicate the error.

**Comment by XiangyuWu** [comment]
@vimalkashore The same error happened to me. Have you found how to fix it?

**Comment by XiangyuWu** [comment]
I solved this problem by downgrading the version of dlib.

**Comment by ilovecv** [comment]
@XiangyuWu Hi, which version of dlib did you use? Thanks.

**Comment by XiangyuWu** [comment]
@ilovecv dlib-19.8.0

**Comment by HuayueZhang** [comment]
> @vimalkashore The same error happened to me. Have you found how to fix it?



> I solved this problem by downgrading the version of dlib.

Do you have the EmotionNet dataset, could you share with me please. Thanks!
