### ISSUE TITLE
About matplotlib

### ISSUE THREAD

**Issue by zoey9594** [albertpumarola/GANimation#15]
I am creating a virtual environment in conda, running the program under python3.5.5
Then my matplotlib is 2.1.1, installed using conda install. When I run test.py, matplotlib often reports an error.
Error is as follows

File "/home/zp/software/miniconda3/envs/meng35/lib/python3.5/site-packages/matplotlib/collections.py", line 26, in <module>
     From . import (_path, artist, cbook, cm, colors as mcolors, docstring,
ImportError: cannot import name _path

I want to ask which version of this code should be in python and the version of matplotlib

**Comment by albertpumarola** [comment]
I've tried with most matplotlib version and all seem to work, this looks more like an external error.
