### ISSUE TITLE
RuntimeError: cuda error: out of memory

### ISSUE THREAD

**Issue by shliang0603** [albertpumarola/GANimation#16]
Use environment:  
Ubuntu16.04
cuda8.0 + cudnn6.0
tensorflow-gpu1.4.1    torch0.4.1

Problem：
I use CK+ dataset to train the Ganimation.But I kept getting the error :"RuntimeError:cuda error : out of memory", and when I changed the batch_size to be larger than the training set, the error stopped.

![image](https://user-images.githubusercontent.com/37186266/44138016-1541d620-a0a5-11e8-81af-2034b5664382.png)

Did anyone make the same mistake  ?

**Comment by albertpumarola** [comment]
If you are running out of memory decrease the batch size to a point it can fit in your GPU memory.

**Comment by shliang0603** [comment]
![image](https://user-images.githubusercontent.com/37186266/44199100-c4cfd300-a175-11e8-96bf-cac9c3c0897b.png)

I use your lasted code and your given sample_dataset . I use command：python train.py --data_dir sample_dataset --name experiment_1 --batch_size 1
The input size is fault, can you give me suggests?

**Comment by albertpumarola** [comment]
Try with batch_size 2, that is the minimum.
