### ISSUE TITLE
Differences between the paper and the code on the generation of fake image

### ISSUE THREAD

**Issue by chenyvehtung** [albertpumarola/GANimation#21]
Hi Albert, thanks for sharing your code. 

In the paper, the fake image is generated by using the equation  
<a href="https://www.codecogs.com/eqnedit.php?latex=I_{y_f}&space;=&space;A&space;\cdot&space;C&space;&plus;&space;(1&space;-&space;A)&space;\cdot&space;I_{y_0}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?I_{y_f}&space;=&space;A&space;\cdot&space;C&space;&plus;&space;(1&space;-&space;A)&space;\cdot&space;I_{y_0}" title="I_{y_f} = A \cdot C + (1 - A) \cdot I_{y_0}" /></a>.

While in the code, I find that the fake image is generated in a different way, which is 
```fake_imgs_masked = fake_img_mask * self._real_img + (1 - fake_img_mask) * fake_imgs```,
refers to https://github.com/albertpumarola/GANimation/blob/master/models/ganimation.py#L228 and https://github.com/albertpumarola/GANimation/blob/master/models/ganimation.py#L275, so it should be 
<a href="https://www.codecogs.com/eqnedit.php?latex=I_{y_f}&space;=&space;A&space;\cdot&space;I_{y_0}&space;&plus;&space;(1&space;-&space;A)&space;\cdot&space;C" target="_blank"><img src="https://latex.codecogs.com/gif.latex?I_{y_f}&space;=&space;A&space;\cdot&space;I_{y_0}&space;&plus;&space;(1&space;-&space;A)&space;\cdot&space;C" title="I_{y_f} = A \cdot I_{y_0} + (1 - A) \cdot C" /></a>

Would you please kindly clarify this? Thanks in advance.

**Comment by albertpumarola** [comment]
It must be like in the paper, I may got an incorrect version of the code when uploading. Thanks for pointing it out, I will check it.

**Comment by ZHANG-SHI-CHANG** [comment]
> 
> 
> Hi Albert, thanks for sharing your code.
> 
> In the paper, the fake image is generated by using the equation
> [![](https://camo.githubusercontent.com/f1f1b533fa48966cc2326023cf4497b2a207bfce/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f495f7b795f667d2673706163653b3d2673706163653b412673706163653b5c63646f742673706163653b432673706163653b2b2673706163653b28312673706163653b2d2673706163653b41292673706163653b5c63646f742673706163653b495f7b795f307d)](https://www.codecogs.com/eqnedit.php?latex=I_{y_f}&space;=&space;A&space;\cdot&space;C&space;+&space;(1&space;-&space;A)&space;\cdot&space;I_{y_0}).
> 
> While in the code, I find that the fake image is generated in a different way, which is
> `fake_imgs_masked = fake_img_mask * self._real_img + (1 - fake_img_mask) * fake_imgs`,
> refers to https://github.com/albertpumarola/GANimation/blob/master/models/ganimation.py#L228 and https://github.com/albertpumarola/GANimation/blob/master/models/ganimation.py#L275, so it should be
> [![](https://camo.githubusercontent.com/9c7a782dc73f1a40f90fdafcf347116bc3bda2b0/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f495f7b795f667d2673706163653b3d2673706163653b412673706163653b5c63646f742673706163653b495f7b795f307d2673706163653b2b2673706163653b28312673706163653b2d2673706163653b41292673706163653b5c63646f742673706163653b43)](https://www.codecogs.com/eqnedit.php?latex=I_{y_f}&space;=&space;A&space;\cdot&space;I_{y_0}&space;+&space;(1&space;-&space;A)&space;\cdot&space;C)
> 
> Would you please kindly clarify this? Thanks in advance.

兄弟，你复现实验的时候有没有遇到attention趋于1的问题，在我实验的过程中论文里的两个约束loss起不到作用，attention还是会趋于1

**Comment by albertpumarola** [comment]
If it is tending to 1, suposing that the dataset is correct, you can try augmenting the lambda of this constraint. Be careful tunning it, if you increase it too much A will be 0 all the time.
