### ISSUE TITLE
Questions about the Attention-based Generator

### ISSUE THREAD

**Issue by taylover-pei** [albertpumarola/GANimation#23]
Congratulations! You have done a great job.
But I have a question about the Attention-based Generator. This paper said that the generator outputs two masks, a color mask C and attention mask A. And you gave the following formula:
![image](https://user-images.githubusercontent.com/27360803/44563850-b6e00a80-a792-11e8-8c74-6a9cbea5148c.png)
So, I'm wondering how did you come up with this formula? I mean, how do you explain this formula?
Looking forward to your apply.

**Comment by chenyvehtung** [comment]
This is somehow a common trick when playing with attention map / attention mask. From my point of view,
  
* Intuitively attention mask enables some specific areas where facial muscle changed to get more focus, applying it to the color mask (<a href="https://www.codecogs.com/eqnedit.php?latex=A&space;\cdot&space;C" target="_blank"><img src="https://latex.codecogs.com/gif.latex?A&space;\cdot&space;C" title="A \cdot C" /></a>) can generate images with clear dynamic area and unclear static area. 
* After that, what left is to enhance the static area, which should be similar between the generated image and the original real image.  So we can enhance the static area (basically it refers to background area) in the original real image (<a href="https://www.codecogs.com/eqnedit.php?latex=(1&space;-&space;A)&space;\cdot&space;I_{y_o}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?(1&space;-&space;A)&space;\cdot&space;I_{y_o}" title="(1 - A) \cdot I_{y_o}" /></a>) and merge it to the above to get final result (<a href="https://www.codecogs.com/eqnedit.php?latex=A&space;\cdot&space;C&space;&plus;&space;(1&space;-&space;A)&space;\cdot&space;I_{y_o}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?A&space;\cdot&space;C&space;&plus;&space;(1&space;-&space;A)&space;\cdot&space;I_{y_o}" title="A \cdot C + (1 - A) \cdot I_{y_o}" /></a>). 

You can understand it more clearly with the help of Sec. 4.1_Generator and Sec. 6.5 of the original paper. 

**However**, the above is what the paper tells, while this project actually implements it in a different (or wrong?) way. You can check out [ Issue #21 ](https://github.com/albertpumarola/GANimation/issues/21) for more details.
