### ISSUE TITLE
Generation AU Problem

### ISSUE THREAD

**Issue by shliang0603** [albertpumarola/GANimation#25]
First，I use the below command line to generation AU 
E:\MagicProject\code\OpenFace_2.0.4_win_x64>FeatureExtraction.exe -f E:\Dataset_processing\20180821_GANimation_CK+\imgs\S005_001_00000001.png  -out_dir E:\out

I generate CSV file of AU is from 679 column to 696，like below
![image](https://user-images.githubusercontent.com/37186266/44627543-38d25e00-a962-11e8-80f6-573cc533b1dd.png)

Finally, I use this to train GANimation. But my train result is not expectation. I suspect that I generation is false.

Today ,I use FeatureExtraction.exe to generate AU ,but I choice different parameter，the command line and generation CSV of Au in below
1. generation AU from column 6 to column 25
E:\MagicProject\code\OpenFace_2.0.4_win_x64>FeatureExtraction.exe -f E:\Dataset_processing\20180821_GANimation_CK+\imgs\S005_001_00000001.png -aus -out_dir E:\

![image](https://user-images.githubusercontent.com/37186266/44627566-ae3e2e80-a962-11e8-8c81-1155275983ac.png)

2.
E:\MagicProject\code\OpenFace_2.0.4_win_x64>FeatureExtraction.exe -f E:\Dataset_processing\20180821_GANimation_CK+\imgs\S005_001_00000001.png -aus -au_static -out_dir E:\out

![image](https://user-images.githubusercontent.com/37186266/44627608-5fdd5f80-a963-11e8-9c1e-f8e894aa689c.png)

But ,today I use 1 and 2 openface command line to generate AU ,the result is different.
(I used the same picture for the AU generation test)

Can you tell me how to use the right openface command parameter to generate CSV of AU.

**Comment by XiangyuWu** [comment]
When inputting your command, _-aus_ is required to limit the _.csv_ only contain the action units information. For more detail you may see the introduction of OpenFace.

**Comment by XiangyuWu** [comment]
I think it is _FaceLandmarkImg_ that you should use.

**Comment by XiangyuWu** [comment]
I don't know how does your question come. In my csv file, content[0] is face, content[1] is confidence, and form content[2] to content[18] is exactly the value of action unit.

**Comment by xiaoiker** [comment]
@XiangyuWu  Sorry, my fault. Thanks very much for pointing out.

**Comment by shliang0603** [comment]
@XiangyuWu  Hi，Xiangyu Wu,Can you send me your the command line of generation AU(action unit).
In my file, generation AU is between 679 column and 696 column

**Comment by XiangyuWu** [comment]
@shliang0603 adding _-aus_ to your command line. For linux platform, my command line is:
_./FaceLandmarkImg -fdir path_to_images -out_dir path_for_generated_files **-aus**_

**Comment by shliang0603** [comment]
Thanks for your answering, I will try again

**Comment by XiangyuWu** [comment]
@ilovecv I didn't pay attention to it, and I tested it just now, the same problem happened to me. I don't know why such differences exist.

**Comment by shliang0603** [comment]
@ilovecv Unfortunately, it is really difficult to ensure the same exact numerical results when using different compilers (e.g. see https://stackoverflow.com/questions/16395615/is-there-any-way-to-make-sure-the-floating-point-arithmetic-result-the-same-in-b), the differences will come from compilers optimizing code differently and possibly different versions of libraries used with different optimization settings (e.g. OpenCV)

**Comment by albertpumarola** [comment]
Closed for inactivity
