### ISSUE TITLE
Trained model is not public?

### ISSUE THREAD

**Issue by leeeeeeo** [albertpumarola/GANimation#3]
@albertpumarola Thank you for your contribution on this work !
When I run the test like this: 
python test.py --input_path ./sample_dataset/imgs/N_0000001507_00202.jpg
It came : 
![image](https://user-images.githubusercontent.com/25877709/43363103-65ca9d80-932f-11e8-8e9d-9000c222d743.png)

And there is an image in output/ like this : 
![image](https://user-images.githubusercontent.com/25877709/43363081-d1db1758-932e-11e8-97ed-232277126fa3.png)

Is the model not public available?
Thank you! Looking forward to your reply.

**Comment by albertpumarola** [comment]
Hi,
For the moment we are not planning to release the trained model as we are working on future improvements. Everything is prepared to be easily trained with any dataset containing faces by following the readme.

**Comment by leeeeeeo** [comment]
@albertpumarola Another question: test images are 128x128 face area. How did you put them back on the original image seamlessly like this : 
![image](https://user-images.githubusercontent.com/25877709/43363176-442c03ec-9331-11e8-889b-f5e3c8c914af.png)

**Comment by albertpumarola** [comment]
If you check the paper you'll see that the model is trained to only change the facial expression without altering the background. To generate these images I do the following:
1. Detect faces with OpenFace
2. Crop the face and resize to 128x128
3. Run it through the model
4. Rescale the edited face to its original size and place it back into the image

**Comment by voa18105** [comment]
@leeeeeeo I have a same error as you mentioned first, how did you solve it?

**Comment by leeeeeeo** [comment]
@voa18105 It's because the trained model is not public available. You need to train your own model to use the test code.

**Comment by voa18105** [comment]
@leeeeeeo yes, i see... now when i've specified the path to a model I've trained - the error is different
