### ISSUE TITLE
AU detections from OpenFace are different from the AU labels in sample dataset

### ISSUE THREAD

**Issue by ilovecv** [albertpumarola/GANimation#32]
Hi,
I run OpenFace on the imgs under sample_dataset folder, and found the AU results are different from the AU labels in aus_openface.pkl. For example, for N_0000000356_00190.jpg, the labels provided by you are: 
[2.86, 2.27, 1.45, 1.1 , 0.  , 0.65, 0.05, 0.  , 0.75, 1.65, 0.6 , 0.  , 1.86, 0.  , 0.62, 0.25, 0.  ], 
while the detected results from OpenFace are:
[0.48, 0.  , 0.  , 1.47, 0.23, 0.06, 0.  , 0.72, 0.48, 1.36, 0.3 , 0.  , 1.76, 0.  , 0.44, 0.78, 0.  ].

I used the command: ./bin/FaceLandmarkImg -fdir GANimation/sample_dataset/imgs -out_dir GANimation/sample_dataset/features -aus

Is it correct?
Thanks!

**Comment by JimmyYing** [comment]
my result is similar
0.45 | 0 | 0 | 1.54 | 0.2 | 0 | 0 | 0.79 | 0.49 | 1.31 | 0.31 | 0 | 1.67 | 0 | 0.43 | 0.91 | 0
@ilovecv

**Comment by albertpumarola** [comment]
Maybe I messed up when uploading to the repo sample dataset... Do not worry, use whatever OpenFace returns. The sample dataset was just to illustrate the required dataset directories structure.
