### ISSUE TITLE
How to add smile to the face with trained model?

### ISSUE THREAD

**Issue by AidasK** [albertpumarola/GANimation#35]
I have trained the model but I can see that desired condition in test.py file is `expression = np.random.uniform(0, 1, opt.cond_nc)`

I am running it as `python test.py --input_path ds/imgcelebaprocessed/000009.jpg --name experiment_128v2`

How can I modify expression of generated output? Have you used different test file which is not shared?

**Comment by huahuachenchen** [comment]
Hi，The aus index of expression maybe is  AU01 AU02 AU04 AU05 AU06 AU07 AU09 AU10 AU12 AU14 AU15 AU17 AU20 AU23 AU25 AU26 AU45，when the Smile‘s aus is 1+6+12+14， set value( range (0,1)) of the correspond index. It can success to gen.

**Comment by AidasK** [comment]
I have tried generating every attribute, but results were pretty bad

```python
def main():
    opt = TestOptions().parse()
    if not os.path.isdir(opt.output_dir):
        os.makedirs(opt.output_dir)

    morph = MorphFacesInTheWild(opt)

    image_path = opt.input_path
    for i in range(0, opt.cond_nc):
        # expression = np.random.uniform(0, 1, opt.cond_nc)
        expression = np.zeros((opt.cond_nc,))
        expression[i] = 5.0
        print(expression)
        morph.morph_file(image_path, expression, i)
```
Original:
![000031](https://user-images.githubusercontent.com/2088484/45357300-94d9eb00-b5ce-11e8-84d6-c2060b215c52.jpg)

Results:
![000031 jpg_9_out](https://user-images.githubusercontent.com/2088484/45357320-a15e4380-b5ce-11e8-9358-3a22ce7141ea.png)
![000031 jpg_8_out](https://user-images.githubusercontent.com/2088484/45357322-a15e4380-b5ce-11e8-9b71-618a48843ced.png)
![000031 jpg_7_out](https://user-images.githubusercontent.com/2088484/45357323-a15e4380-b5ce-11e8-826a-f4ad508465d5.png)
![000031 jpg_6_out](https://user-images.githubusercontent.com/2088484/45357324-a1f6da00-b5ce-11e8-8bd6-f6908e1c1705.png)
![000031 jpg_5_out](https://user-images.githubusercontent.com/2088484/45357325-a1f6da00-b5ce-11e8-954a-da510b2a447b.png)
![000031 jpg_4_out](https://user-images.githubusercontent.com/2088484/45357327-a28f7080-b5ce-11e8-95e8-3db4619fbcae.png)
![000031 jpg_3_out](https://user-images.githubusercontent.com/2088484/45357328-a28f7080-b5ce-11e8-9002-682bbccf2fac.png)
![000031 jpg_2_out](https://user-images.githubusercontent.com/2088484/45357330-a3280700-b5ce-11e8-9efc-397b557eb17f.png)
![000031 jpg_1_out](https://user-images.githubusercontent.com/2088484/45357334-a3c09d80-b5ce-11e8-9085-3ca59d456c97.png)
![000031 jpg_16_out](https://user-images.githubusercontent.com/2088484/45357335-a4593400-b5ce-11e8-9e0d-144ac61691c9.png)
![000031 jpg_15_out](https://user-images.githubusercontent.com/2088484/45357337-a4593400-b5ce-11e8-9d39-19f11caace60.png)
![000031 jpg_14_out](https://user-images.githubusercontent.com/2088484/45357338-a4593400-b5ce-11e8-9039-aa5040c1135a.png)
![000031 jpg_13_out](https://user-images.githubusercontent.com/2088484/45357339-a4593400-b5ce-11e8-980a-5ffa9936c79a.png)
![000031 jpg_12_out](https://user-images.githubusercontent.com/2088484/45357340-a4f1ca80-b5ce-11e8-815c-29e78251bfc4.png)
![000031 jpg_11_out](https://user-images.githubusercontent.com/2088484/45357342-a4f1ca80-b5ce-11e8-9fc2-7ec8a6d30df8.png)
![000031 jpg_10_out](https://user-images.githubusercontent.com/2088484/45357343-a4f1ca80-b5ce-11e8-9c75-ee2a6e000842.png)
![000031 jpg_0_out](https://user-images.githubusercontent.com/2088484/45357344-a4f1ca80-b5ce-11e8-8312-90a13dbe3539.png)

**Comment by AidasK** [comment]
Second try, I have used current action units of the face and modified only one of them. Results are better, but nothing spectacular.


```python
def main():
    opt = TestOptions().parse()
    if not os.path.isdir(opt.output_dir):
        os.makedirs(opt.output_dir)

    morph = MorphFacesInTheWild(opt)

    image_path = opt.input_path
    for i in range(0, opt.cond_nc):
        expression = np.array([float(e) for e in opt.cond.split(',')])
        expression[i] = 5.0
        morph.morph_file(image_path, expression, i)
```
`opt.cond.split(',')` are unmodified action units for a current face.

Results:
![000031 jpg_9_out](https://user-images.githubusercontent.com/2088484/45358319-c4d6bd80-b5d1-11e8-8e1e-95125a050f57.png)
![000031 jpg_8_out](https://user-images.githubusercontent.com/2088484/45358320-c56f5400-b5d1-11e8-8d0e-392feb28ab46.png)
![000031 jpg_7_out](https://user-images.githubusercontent.com/2088484/45358321-c56f5400-b5d1-11e8-87c8-0f42e4c0f8b6.png)
![000031 jpg_6_out](https://user-images.githubusercontent.com/2088484/45358322-c56f5400-b5d1-11e8-9172-ea01ad137896.png)
![000031 jpg_5_out](https://user-images.githubusercontent.com/2088484/45358323-c56f5400-b5d1-11e8-93a4-bbd9e08742ce.png)
![000031 jpg_4_out](https://user-images.githubusercontent.com/2088484/45358324-c56f5400-b5d1-11e8-911a-f4bddf3f69da.png)
![000031 jpg_3_out](https://user-images.githubusercontent.com/2088484/45358325-c56f5400-b5d1-11e8-8773-78609b99e08d.png)
![000031 jpg_2_out](https://user-images.githubusercontent.com/2088484/45358326-c607ea80-b5d1-11e8-927e-55409180e542.png)
![000031 jpg_1_out](https://user-images.githubusercontent.com/2088484/45358327-c607ea80-b5d1-11e8-8104-964b7564436b.png)
![000031 jpg_16_out](https://user-images.githubusercontent.com/2088484/45358328-c607ea80-b5d1-11e8-8245-f2ae4e5ea496.png)
![000031 jpg_15_out](https://user-images.githubusercontent.com/2088484/45358330-c607ea80-b5d1-11e8-84d5-3cf961e1e42d.png)
![000031 jpg_14_out](https://user-images.githubusercontent.com/2088484/45358331-c607ea80-b5d1-11e8-9366-f12226921269.png)
![000031 jpg_13_out](https://user-images.githubusercontent.com/2088484/45358332-c6a08100-b5d1-11e8-9f51-ce8801436f32.png)
![000031 jpg_12_out](https://user-images.githubusercontent.com/2088484/45358333-c6a08100-b5d1-11e8-973a-5ce6f24994cb.png)
![000031 jpg_11_out](https://user-images.githubusercontent.com/2088484/45358334-c6a08100-b5d1-11e8-9def-8302b4c21901.png)
![000031 jpg_10_out](https://user-images.githubusercontent.com/2088484/45358336-c6a08100-b5d1-11e8-8c5a-a5a4f07eff2a.png)
![000031 jpg_0_out](https://user-images.githubusercontent.com/2088484/45358338-c6a08100-b5d1-11e8-9fb3-641f3ba8308b.png)

**Comment by huahuachenchen** [comment]
when use neutral， maybe better ，but when use other expression， it were bad.
my result:
initial           Disgust         happy      sad
![0_test_2393](https://user-images.githubusercontent.com/42829556/45400673-aaf3b400-b67f-11e8-9a22-51f82e31cd95.png)
![disgust](https://user-images.githubusercontent.com/42829556/45400674-aaf3b400-b67f-11e8-89b6-f1691739c47f.png)
![happy](https://user-images.githubusercontent.com/42829556/45400675-ab8c4a80-b67f-11e8-8b7d-39641dd1e4be.png)
![sad](https://user-images.githubusercontent.com/42829556/45400676-ab8c4a80-b67f-11e8-976d-d5ff73ba3633.png)

initial     Disgust           sad                fear             Suprise
![0_test_0502](https://user-images.githubusercontent.com/42829556/45400743-f60dc700-b67f-11e8-9ddd-beadf9e816f6.png)
![disgust0_test_0502 png_out](https://user-images.githubusercontent.com/42829556/45400745-f6a65d80-b67f-11e8-9a31-74f697dffefc.png)
![fear0_test_0502 png_out](https://user-images.githubusercontent.com/42829556/45400746-f6a65d80-b67f-11e8-86d4-1eb8c00b6b6f.png)
![sad0_test_0502 png_out](https://user-images.githubusercontent.com/42829556/45400748-f7d78a80-b67f-11e8-95ec-bd1a7eab6297.png)
![surprise_0_test_0502 png_out](https://user-images.githubusercontent.com/42829556/45400749-f8702100-b67f-11e8-931a-44ec66e4ab93.png)

**Comment by albertpumarola** [comment]
The easiest way to get the desired expression is to use the AUs values of another person with the desired expression. In this way, you ensure that the values are human-feasible. 
Looks like you have a neutral expression bias. This can be easily solved by balancing your dataset.

**Comment by c1a1o1** [comment]
How long does it take to apply for EmotionNet data set?
