### ISSUE TITLE
Could you make your trained model(.pth) available?

### ISSUE THREAD

**Issue by LittleWat** [albertpumarola/GANimation#36]
Thank you for your novel work! I would like to try this on my laptop. It would be very nice if you make your trained model(.pth) available. Thanks in advance.

**Comment by albertpumarola** [comment]
Hi,
For the moment we are not planning to release the trained model as we are working on future improvements. Everything is prepared to be easily trained with any dataset containing faces. The readme contains all the instructions.

**Comment by LittleWat** [comment]
Thank for your replay. I have no GPUs but I will try using Colab.
