### ISSUE TITLE
Matplotlib 3.0+ does not support Python 2.x, 3.0, 3.1, 3.2, 3.3, or 3.4.     Beginning with Matplotlib 3.0, Python 3.5 and above is required.          This may be due to an out of date pip.          Make sure you have pip >= 9.0.1.

### ISSUE THREAD

**Issue by jackylee1** [albertpumarola/GANimation#40]
Matplotlib 3.0+ does not support Python 2.x, 3.0, 3.1, 3.2, 3.3, or 3.4.
    Beginning with Matplotlib 3.0, Python 3.5 and above is required.
    
    This may be due to an out of date pip.
    
    Make sure you have pip >= 9.0.1.
so i upgrade python to python3.6 in order to install Matplotlib 3.0
however,i start to train with bash launch/run_train.sh
launch/run_train.sh: line 3: python: command not found
how can i solve this

**Comment by albertpumarola** [comment]
The code was designed for Python 2.7
