### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by jackylee1** [albertpumarola/GANimation#41]
python3 train.py  --data_dir sample_dataset  --name experiment_1  --batch_size 25 
------------ Options -------------
D_adam_b1: 0.5
D_adam_b2: 0.999
G_adam_b1: 0.5
G_adam_b2: 0.999
aus_file: aus_openface.pkl
batch_size: 25
checkpoints_dir: ./checkpoints
cond_nc: 17
data_dir: sample_dataset
dataset_mode: aus
display_freq_s: 300
do_saturate_mask: False
gpu_ids: [0]
image_size: 128
images_folder: imgs
is_train: True
lambda_D_cond: 4000
lambda_D_gp: 10
lambda_D_prob: 1
lambda_cyc: 10
lambda_mask: 0.1
lambda_mask_smooth: 1e-05
load_epoch: 0
lr_D: 0.0001
lr_G: 0.0001
model: ganimation
n_threads_test: 1
n_threads_train: 4
name: experiment_1
nepochs_decay: 10
nepochs_no_decay: 20
num_iters_validate: 1
poses_g_sigma: 0.06
print_freq_s: 60
save_latest_freq_s: 3600
serial_batches: False
test_ids_file: test_ids.csv
train_G_every_n_iterations: 5
train_ids_file: train_ids.csv
-------------- End ----------------
./checkpoints/experiment_1
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    Train()
  File "train.py", line 13, in __init__
    data_loader_train = CustomDatasetDataLoader(self._opt, is_for_train=True)
  File "/root/GANimation/data/custom_dataset_data_loader.py", line 10, in __init__
    self._create_dataset()
  File "/root/GANimation/data/custom_dataset_data_loader.py", line 13, in _create_dataset
    self._dataset = DatasetFactory.get_by_name(self._opt.dataset_mode, self._opt, self._is_for_train)
  File "/root/GANimation/data/dataset.py", line 16, in get_by_name
    dataset = AusDataset(opt, is_for_train)
  File "/root/GANimation/data/dataset_aus.py", line 17, in __init__
    self._read_dataset_paths()
  File "/root/GANimation/data/dataset_aus.py", line 66, in _read_dataset_paths
    self._conds = self._read_conds(conds_filepath)
  File "/root/GANimation/data/dataset_aus.py", line 93, in _read_conds
    return pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 0: ordinal not in range(128)

**Comment by hysts** [comment]
I think that's because you are using Python 3, while `sample_dataset/auc_openface.pkl` seems to be pickled in Python 2. Replacing `pickle.load(f)` with `pickle.load(f, encoding='latin1')` would solve the problem.
https://stackoverflow.com/questions/11305790/pickle-incompatibility-of-numpy-arrays-between-python-2-and-3/41366785#41366785

**Comment by albertpumarola** [comment]
Yes, I used Python 2.7.
