### ISSUE TITLE
the result below,i don't see any difference

### ISSUE THREAD

**Issue by jackylee1** [albertpumarola/GANimation#43]
![oli jpg_out](https://user-images.githubusercontent.com/3367277/46079980-36665c80-c1cb-11e8-80a3-602bc9691192.png)

**Comment by albertpumarola** [comment]
Looks like you did not train the model, you have to train it first.

**Comment by jackylee1** [comment]
i have train it with the provided sample_dataset

**Comment by albertpumarola** [comment]
the sample dataset only contains 4 images, minimum minimum minimum you need 10K if you do a good data augmentation. In my case I used 200K samples.

**Comment by jackylee1** [comment]
thanks,as to my other questions in #45 .hopefully to get your help.
if the process is right ,then that's the  problem of sample number

**Comment by jackylee1** [comment]
and in openface ,the command $ build/bin/FaceLandmarkImg -f sample1.jpg

it only process one image one time.
how to solve it with 200K images?

**Comment by jas0n1ee** [comment]
@jackylee1 FaceLandmarkImg has an argument `fdir`
