### ISSUE TITLE
Lots of skipped images

### ISSUE THREAD

**Issue by Morpheus3000** [albertpumarola/GANimation#44]
Hello,

I am trying to recreate the experiment. But when I run the pipeline, I see a lot of skipped samples. I traced the error and found that it is because the image loader has the 3 channel checks. So it seems there are a lot of grayscale images in the data. So I was wondering if you have your train/test split filenames available somewhere. It would be nice to be able to use those and download those images, to make sure that I get proper 3 channel images and have the training run properly.

**Comment by albertpumarola** [comment]
Yes, I filter the low res and grayscale images prior to training.

**Comment by ZHUTAO142857** [comment]
> Yes, I filter the low res and grayscale images prior to training.

will this kind of images influence the result?
