### ISSUE TITLE
more problem.

### ISSUE THREAD

**Issue by jackylee1** [albertpumarola/GANimation#46]
python train.py  --data_dir mydata --name experiment_1 --batch_size 25
------------ Options -------------
D_adam_b1: 0.5
D_adam_b2: 0.999
G_adam_b1: 0.5
G_adam_b2: 0.999
aus_file: aus_openface.pkl
batch_size: 25
checkpoints_dir: ./checkpoints
cond_nc: 17
data_dir: mydata
dataset_mode: aus
display_freq_s: 300
do_saturate_mask: False
gpu_ids: [0]
image_size: 128
images_folder: imgs
is_train: True
lambda_D_cond: 4000
lambda_D_gp: 10
lambda_D_prob: 1
lambda_cyc: 10
lambda_mask: 0.1
lambda_mask_smooth: 1e-05
load_epoch: 0
lr_D: 0.0001
lr_G: 0.0001
model: ganimation
n_threads_test: 1
n_threads_train: 4
name: experiment_1
nepochs_decay: 10
nepochs_no_decay: 20
num_iters_validate: 1
poses_g_sigma: 0.06
print_freq_s: 60
save_latest_freq_s: 3600
serial_batches: False
test_ids_file: test_ids.csv
train_G_every_n_iterations: 5
train_ids_file: train_ids.csv
-------------- End ----------------
./checkpoints/experiment_1
Dataset AusDataset was created
Dataset AusDataset was created
#train images = 91
#test images = 91
Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
Model GANimation was created
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    Train()
  File "train.py", line 27, in __init__
    self._train()
  File "train.py", line 40, in _train
    self._train_epoch(i_epoch)
  File "train.py", line 69, in _train_epoch
    self._model.optimize_parameters(keep_data_for_visuals=do_visuals, train_generator=train_generator)
  File "/data/GANimation/models/ganimation.py", line 207, in optimize_parameters
    loss_D, fake_imgs_masked = self._forward_D()
  File "/data/GANimation/models/ganimation.py", line 278, in _forward_D
    d_real_img_prob, d_real_img_cond = self._D.forward(self._real_img)
  File "/data/GANimation/networks/discriminator_wasserstein_gan.py", line 29, in forward
    out_aux = self.conv2(h)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    finalizer()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    self.padding, self.dilation, self.groups)
RuntimeError: sizes must be non-negative

**Comment by jackylee1** [comment]
and 
root@0bb78f42cc13:/data/GANimation# python train.py  --data_dir mydata --name experiment_1 --batch_size 25
------------ Options -------------
D_adam_b1: 0.5
D_adam_b2: 0.999
G_adam_b1: 0.5
G_adam_b2: 0.999
aus_file: aus_openface.pkl
batch_size: 25
checkpoints_dir: ./checkpoints
cond_nc: 17
data_dir: mydata
dataset_mode: aus
display_freq_s: 300
do_saturate_mask: False
gpu_ids: [0]
image_size: 128
images_folder: imgs
is_train: True
lambda_D_cond: 4000
lambda_D_gp: 10
lambda_D_prob: 1
lambda_cyc: 10
lambda_mask: 0.1
lambda_mask_smooth: 1e-05
load_epoch: 0
lr_D: 0.0001
lr_G: 0.0001
model: ganimation
n_threads_test: 1
n_threads_train: 4
name: experiment_1
nepochs_decay: 10
nepochs_no_decay: 20
num_iters_validate: 1
poses_g_sigma: 0.06
print_freq_s: 60
save_latest_freq_s: 3600
serial_batches: False
test_ids_file: test_ids.csv
train_G_every_n_iterations: 5
train_ids_file: train_ids.csv
-------------- End ----------------
./checkpoints/experiment_1
Dataset AusDataset was created
Dataset AusDataset was created
#train images = 90
#test images = 90
Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
Model GANimation was created
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    Train()
  File "train.py", line 27, in __init__
    self._train()
  File "train.py", line 40, in _train
    self._train_epoch(i_epoch)
  File "train.py", line 69, in _train_epoch
    self._model.optimize_parameters(keep_data_for_visuals=do_visuals, train_generator=train_generator)
  File "/data/GANimation/models/ganimation.py", line 207, in optimize_parameters
    loss_D, fake_imgs_masked = self._forward_D()
  File "/data/GANimation/models/ganimation.py", line 278, in _forward_D
    d_real_img_prob, d_real_img_cond = self._D.forward(self._real_img)
  File "/data/GANimation/networks/discriminator_wasserstein_gan.py", line 29, in forward
    out_aux = self.conv2(h)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: sizes must be non-negative
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    finalizer()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    finalizer()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: '/tmp/pymp-N19tvE/.nfs000000000c9422aa000016ae'
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 16] Device or resource busy: '/tmp/pymp-Y1vDeq/.nfs000000000c942298000016af'

**Comment by albertpumarola** [comment]
Your input images batches must be of size Bx3x128x128.

**Comment by jackylee1** [comment]
------------ Options -------------
D_adam_b1: 0.5
D_adam_b2: 0.999
G_adam_b1: 0.5
G_adam_b2: 0.999
aus_file: aus_openface.pkl
batch_size: 25
checkpoints_dir: ./checkpoints
cond_nc: 17
data_dir: test400
dataset_mode: aus
display_freq_s: 300
do_saturate_mask: False
gpu_ids: [0]
image_size: 128
images_folder: imgs
is_train: True
lambda_D_cond: 4000
lambda_D_gp: 10
lambda_D_prob: 1
lambda_cyc: 10
lambda_mask: 0.1
lambda_mask_smooth: 1e-05
load_epoch: 0
lr_D: 0.0001
lr_G: 0.0001
model: ganimation
n_threads_test: 1
n_threads_train: 4
name: experiment_1
nepochs_decay: 10
nepochs_no_decay: 20
num_iters_validate: 1
poses_g_sigma: 0.06
print_freq_s: 60
save_latest_freq_s: 3600
serial_batches: False
test_ids_file: test_ids.csv
train_G_every_n_iterations: 5
train_ids_file: train_ids.csv
-------------- End ----------------
./checkpoints/experiment_1
Dataset AusDataset was created
Dataset AusDataset was created
#train images = 397
#test images = 397
Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
Model GANimation was created
error reading image 000121, skipping sample
error reading image 000278, skipping sample
error reading image 000306, skipping sample
error reading image 000062, skipping sample
error reading image 000145, skipping sample
error reading image 000370, skipping sample
error reading image 000201, skipping sample
error reading image 000232, skipping sample
error reading image 000219, skipping sample
error reading image 000096, skipping sample
error reading image 000367, skipping sample
error reading image 000143, skipping sample
error reading image 000136, skipping sample
error reading image 000029, skipping sample
error reading image 000351, skipping sample
error reading image 000235, skipping sample
error reading image 000135, skipping sample
error reading image 000052, skipping sample
error reading image 000339, skipping sample
error reading image 000249, skipping sample
error reading image 000184, skipping sample
error reading image 000172, skipping sample
error reading image 000185, skipping sample
error reading image 000081, skipping sample
error reading image 000359, skipping sample
error reading image 000257, skipping sample
error reading image 000246, skipping sample
error reading image 000118, skipping sample
error reading image 000098, skipping sample
error reading image 000111, skipping sample
error reading image 000397, skipping sample
error reading image 000151, skipping sample
error reading image 000383, skipping sample
error reading image 000061, skipping sample
error reading image 000257, skipping sample
error reading image 000237, skipping sample
error reading image 000172, skipping sample
error reading image 000005, skipping sample
error reading image 000363, skipping sample
error reading image 000005, skipping sample
error reading image 000081, skipping sample
error reading image 000332, skipping sample
error reading image 000205, skipping sample
error reading image 000113, skipping sample
error reading image 000290, skipping sample
error reading image 000109, skipping sample
error reading image 000023, skipping sample
error reading image 000306, skipping sample
error reading image 000099, skipping sample
error reading image 000028, skipping sample
error reading image 000262, skipping sample
error reading image 000093, skipping sample
error reading image 000388, skipping sample
error reading image 000357, skipping sample
error reading image 000262, skipping sample
error reading image 000047, skipping sample
error reading image 000098, skipping sample
error reading image 000391, skipping sample
error reading image 000069, skipping sample
error reading image 000290, skipping sample
error reading image 000023, skipping sample
error reading image 000078, skipping sample
error reading image 000092, skipping sample
error reading image 000273, skipping sample
error reading image 000191, skipping sample
error reading image 000124, skipping sample
error reading image 000379, skipping sample
error reading image 000346, skipping sample
error reading image 000114, skipping sample
error reading image 000121, skipping sample
error reading image 000328, skipping sample
error reading image 000389, skipping sample
error reading image 000031, skipping sample
error reading image 000360, skipping sample
error reading image 000165, skipping sample
error reading image 000145, skipping sample
error reading image 000099, skipping sample
error reading image 000085, skipping sample
error reading image 000175, skipping sample
error reading image 000032, skipping sample
error reading image 000155, skipping sample
error reading image 000175, skipping sample
error reading image 000138, skipping sample
error reading image 000197, skipping sample
error reading image 000123, skipping sample
error reading image 000096, skipping sample
error reading image 000005, skipping sample
error reading image 000391, skipping sample
error reading image 000047, skipping sample
error reading image 000165, skipping sample
error reading image 000343, skipping sample
error reading image 000304, skipping sample
error reading image 000344, skipping sample
error reading image 000024, skipping sample
error reading image 000337, skipping sample
error reading image 000162, skipping sample
error reading image 000184, skipping sample
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    Train()
  File "train.py", line 27, in __init__
    self._train()
  File "train.py", line 40, in _train
    self._train_epoch(i_epoch)
  File "train.py", line 59, in _train_epoch
    for i_train_batch, train_batch in enumerate(self._dataset_train):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 184, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 184, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 173, in default_collate
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
RuntimeError: cannot unsqueeze empty tensor




why is that, the size is as you mentioned

**Comment by albertpumarola** [comment]
I see a lot of skipped images in your log, this happens when the image is not in the provided dataset path, check that the dataset path is correct. What it may be happening is that the data loader is not being able to read any image.

**Comment by yangzhikai** [comment]
@albertpumarola @jackylee1 I think you should check input image, the openface output of mine is *.bmp.

**Comment by albertpumarola** [comment]
Closed for inactivity
