### ISSUE TITLE
Regarding tuning the hyper-parameters

### ISSUE THREAD

**Issue by yunfan0621** [albertpumarola/GANimation#48]
Hi @albertpumarola ,

Thank you for sharing your great work! 

I am recently working on migrating the idea of your work to other tasks related to face attribute editing. However, I am struggling with searching for hyper-parameters to obtain good results as there are too many to tune. Would you kindly share some experiences on tuning your model (e.g. which terms is the most important one? what is the key point?).

To get some knowledge of reasonable losses, I will appreciate it if you could share some log information of training your final model. I just would like to know the scales and relationships between those loss terms.

Thank you in advance!

**Comment by albertpumarola** [comment]
I recommend first scaling all losses to have the same range of values in the first iterations and train to see what happens. Then, start playing with giving a bit more importance to specific terms.
