### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by staceycy** [albertpumarola/GANimation#5]
Hi, thank you very much for sharing your training and testing codes. 
Could you please also share the training data? 
I have applied for the training data on the website but still get no reply. 
Thank you very much.

**Comment by albertpumarola** [comment]
Sorry, I am not the dataset owner. I only have a license to use it, but not to share it. I'm sure they will answer you in a few days.

**Comment by HuayueZhang** [comment]
> Hi, thank you very much for sharing your training and testing codes.
> Could you please also share the training data?
> I have applied for the training data on the website but still get no reply.
> Thank you very much.

Hello, I am also waiting for the reply for months.  I am so sad. Do you have the dataset now? Could you share with me? Thanks! 
My email:  xjtuzhy@outlook.com

**Comment by imjiangjun** [comment]
@HuayueZhang Hi, have you got the dataset now?

**Comment by IamMegatron2025** [comment]
@staceycy Could you share the training dataset with me? Thanks!
My email: zhentingGong@outlook.com

**Comment by staceycy** [comment]
@IvyGongoogle  Sorry, I didn't get the data. :(

**Comment by IamMegatron2025** [comment]
it is a sad thing

**Comment by vipermu** [comment]
You can find preprocessed data and pretrained models here: https://github.com/vipermu/ganimation

**Comment by IamMegatron2025** [comment]
> You can find preprocessed data and pretrained models here: https://github.com/vipermu/ganimation

it is only the dataset `celeba`,  but can not find preprocessed data about `EmotionNet`

**Comment by vipermu** [comment]
> > You can find preprocessed data and pretrained models here: https://github.com/vipermu/ganimation
> 
> it is only the dataset `celeba`, but can not find preprocessed data about `EmotionNet`

It does the job. EmotionNet is not a public dataset.

**Comment by bsmith0003** [comment]
I asked for dataset but I have not received it, it seems very hard to obtain it

**Comment by vipermu** [comment]
> I asked for dataset but I have not received it, it seems very hard to obtain it

You can get pretty good results with celeba. I think that the only cool thing about emotionNet is the number of samples and high variability that it presents, but you need to crop the face region and re-compute the AUs anyway, so any dataset with faces should work. You can just find other datasets or create your own one and do the required preprocessing. I uploaded the preprocessed celeba to avoid all that stuff though.

**Comment by bsmith0003** [comment]
yeah probably you're right, but Emotionnet has a huge number of manually annotated images!

**Comment by IamMegatron2025** [comment]
@vipermu  training without efficient epochs on emotionNet seems not to have  a good performance. Like I get the [problem](https://github.com/donydchen/ganimation_replicate/issues/14).  So emotionNet dataset is necessary?

**Comment by vipermu** [comment]
> @vipermu training without efficient epochs on emotionNet seems not to have a good performance. Like I get the [problem](https://github.com/donydchen/ganimation_replicate/issues/14). So emotionNet dataset is necessary?

What do you mean by efficient epochs? I think that if you get enough data with enough variance on it the performance of the model will be the same.

**Comment by IamMegatron2025** [comment]
@vipermu Thanks for your reply. So `celeba` is enough data with enough variance?

**Comment by vipermu** [comment]
> @vipermu Thanks for your reply. So `celeba` is enough data with enough variance?

Unfortunately, the variance in the images is really low but I think that there are enough samples to have something working. The performance won't be the same as the results on the paper, but you can get some decent results.

**Comment by vipermu** [comment]
> @vipermu Thanks for your reply. So `celeba` is enough data with enough variance?

These results were generated with celeba: https://github.com/vipermu/ganimation/blob/master/video_results/standard_celeba.avi
