### ISSUE TITLE
Which pytorch version is used when training

### ISSUE THREAD

**Issue by jas0n1ee** [albertpumarola/GANimation#51]
It seems to me that later pytorch will have some problem when training like poping runtime error "sizes must be non-negative". I was using the latest one which is 0.4.1 and trying to debug on 0.3.1 now. Just want to be sure.

**Comment by yangzhikai** [comment]
@jas0n1ee I have try  pytorch 0.3.1,but it encounter a error in "display visualizer". Then I  modified ganimation.py   in  Iine-346   def get_current_visuals(self):  , and  add   "np.transpose(image_numpy,(2,0,1))" after numpy of OrderedDict()。。
