### ISSUE TITLE
Size mismatch

### ISSUE THREAD

**Issue by dhruv5995** [albertpumarola/GANimation#53]
./checkpoints/experiment_1
Dataset AusDataset was created
Dataset AusDataset was created
#train images = 200000
#test images = 2055
Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
Model GANimation was created
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    Train()
  File "train.py", line 27, in __init__
    self._train()
  File "train.py", line 40, in _train
    self._train_epoch(i_epoch)
  File "train.py", line 69, in _train_epoch
    self._model.optimize_parameters(keep_data_for_visuals=do_visuals, train_generator=train_generator)
  File "/home/ubuntu/GANimation/models/ganimation.py", line 207, in optimize_parameters
    loss_D, fake_imgs_masked = self._forward_D()
  File "/home/ubuntu/GANimation/models/ganimation.py", line 275, in _forward_D
    fake_imgs_masked = fake_img_mask * self._real_img + (1 - fake_img_mask) * fake_imgs
RuntimeError: The size of tensor a (176) must match the size of tensor b (178) at non-singleton dimension 3

I checked the shapes for more detail:
(Pdb) fake_img_mask.shape
torch.Size([25, 1, 216, 176])
(Pdb) fake_imgs.shape
torch.Size([25, 3, 216, 176])
(Pdb) self._real_img.shape
torch.Size([25, 3, 218, 178])

**Comment by albertpumarola** [comment]
Seems that the input dimensions you are using are not valid for the network architecture check for the evolution of the shape across the forward pass.
