### ISSUE TITLE
result not good

### ISSUE THREAD

**Issue by ZHUTAO142857** [albertpumarola/GANimation#54]
I just train and test the model  by the rule written on the webpage. 
I use FaceLandmarkImg.exe
FaceLandmarkImg.exe -nomask -fdir "C:/imgs"
to create AUs and *.csv files while I use sequences of pictures of Obama. 
I set 400 images in train_ids.csv, and 100 images to test_ids.csv.
The traing process is going on smoothly.
Then, I use the 
sudo python test.py --input_path /home/zt/GANimation-master/dataset/imgs/frame_det_00_000489.jpg
to see the model's quality.
At first, a waring come out:
------------------------------------------------------------------------------
./checkpoints/experiment_1
Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
loaded net: ./checkpoints/experiment_1/net_epoch_30_id_G.pth
Model GANimation was created
/home/zt/GANimation-master/models/ganimation.py:127: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  real_img = Variable(self._input_real_img, volatile=True)
/home/zt/GANimation-master/models/ganimation.py:128: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  real_cond = Variable(self._input_real_cond, volatile=True)
/home/zt/GANimation-master/models/ganimation.py:129: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  desired_cond = Variable(self._input_desired_cond, volatile=True)
--------------------------------------------------------------------------------------
So I delete 'volatile=True' in ganimation.py
Again, I write the command:
sudo python test.py --input_path /home/zt/GANimation-master/dataset/imgs/frame_det_00_000489.jpg
The warning was fixed. 
----------------------------------------------------------------------------------------------
./checkpoints/experiment_1
Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
loaded net: ./checkpoints/experiment_1/net_epoch_30_id_G.pth
Model GANimation was created
------------------------------------------------------------------------------------
However, the frame_det_00_000489.jpg_out.png looks not good. The image is blurry and the facial expression is not changed
I am confused.

**Comment by jackylee1** [comment]
not enough images,at least 200000 images needed.
i want to know how you process the images,did you make them 128*128 and how?
my qq is 981687874.

**Comment by ZHUTAO142857** [comment]
> not enough images,at least 200000 images needed.
> i want to know how you process the images,did you make them 128*128 and how?
> my qq is 981687874.
About processing the images.
Firstly, I download a Obama speech from youtube. And use 
FeatureExtraction.exe -nomask -simsize 128 -f "c:/Obama.avi"
to generate sequence images.
Then I use
FaceLandmarkImg.exe -nomask -fdir "C:/imgs"
to generate csv files and images for training.

**Comment by ZHUTAO142857** [comment]
I am confused About the sample_dataset. Is that means I should prepare images from different people?
Or I just prepare one person's images, like 160000 images for train, 40000 images for test.

**Comment by albertpumarola** [comment]
This code was made for Pytorch 0.3.1. Data is everything, if you are having bad results it is because of the dataset. It is not about samples quantity but samples quality. Try cleaning your dataset of low-res images, grayscale images, etc.
