### ISSUE TITLE
still got the error?any possibility to share the training data?

### ISSUE THREAD

**Issue by jackylee1** [albertpumarola/GANimation#55]
------------ Options -------------
D_adam_b1: 0.5
D_adam_b2: 0.999
G_adam_b1: 0.5
G_adam_b2: 0.999
aus_file: aus_openface.pkl
batch_size: 25
checkpoints_dir: ./checkpoints
cond_nc: 17
data_dir: test400
dataset_mode: aus
display_freq_s: 300
do_saturate_mask: False
gpu_ids: [0]
image_size: 128
images_folder: imgs
is_train: True
lambda_D_cond: 4000
lambda_D_gp: 10
lambda_D_prob: 1
lambda_cyc: 10
lambda_mask: 0.1
lambda_mask_smooth: 1e-05
load_epoch: 0
lr_D: 0.0001
lr_G: 0.0001
model: ganimation
n_threads_test: 1
n_threads_train: 4
name: experiment_1
nepochs_decay: 10
nepochs_no_decay: 20
num_iters_validate: 1
poses_g_sigma: 0.06
print_freq_s: 60
save_latest_freq_s: 3600
serial_batches: False
test_ids_file: test_ids.csv
train_G_every_n_iterations: 5
train_ids_file: train_ids.csv
-------------- End ----------------
./checkpoints/experiment_1
Dataset AusDataset was created
Dataset AusDataset was created
#train images = 397
#test images = 397
Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
Model GANimation was created
/content/drive/app/GANimation-master/drive/app/GANimation-master/drive/app/GANimation-master/models/ganimation.py:320: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('g_mskd_fake', self._loss_g_masked_fake.data[0]),
/content/drive/app/GANimation-master/drive/app/GANimation-master/drive/app/GANimation-master/models/ganimation.py:321: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('g_mskd_cond', self._loss_g_masked_cond.data[0]),
/content/drive/app/GANimation-master/drive/app/GANimation-master/drive/app/GANimation-master/models/ganimation.py:322: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('g_cyc', self._loss_g_cyc.data[0]),
/content/drive/app/GANimation-master/drive/app/GANimation-master/drive/app/GANimation-master/models/ganimation.py:326: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('g_m1', self._loss_g_mask_1.data[0]),
/content/drive/app/GANimation-master/drive/app/GANimation-master/drive/app/GANimation-master/models/ganimation.py:327: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('g_m2', self._loss_g_mask_2.data[0]),
/content/drive/app/GANimation-master/drive/app/GANimation-master/drive/app/GANimation-master/models/ganimation.py:328: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('g_m1_s', self._loss_g_mask_1_smooth.data[0]),
/content/drive/app/GANimation-master/drive/app/GANimation-master/drive/app/GANimation-master/models/ganimation.py:329: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('g_m2_s', self._loss_g_mask_2_smooth.data[0]),
/content/drive/app/GANimation-master/drive/app/GANimation-master/drive/app/GANimation-master/models/ganimation.py:331: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('d_real', self._loss_d_real.data[0]),
/content/drive/app/GANimation-master/drive/app/GANimation-master/drive/app/GANimation-master/models/ganimation.py:332: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('d_cond', self._loss_d_cond.data[0]),
/content/drive/app/GANimation-master/drive/app/GANimation-master/drive/app/GANimation-master/models/ganimation.py:333: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('d_fake', self._loss_d_fake.data[0]),
/content/drive/app/GANimation-master/drive/app/GANimation-master/drive/app/GANimation-master/models/ganimation.py:334: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  ('d_gp', self._loss_d_gp.data[0])])
[23/10/2018 08:09:00] (Tv, epoch: 1, it: 0/15, t/smpl: 0.307s) g_fake:0.000 g_cond:0.000 g_mskd_fake:-0.005 g_mskd_cond:15530.584 g_cyc:3.774 g_rgb:0.000 g_rgb_un:0.000 g_rgb_s:0.000 g_m1:0.056 g_m2:0.056 g_m1_s:0.724 g_m2_s:0.712 g_idt:0.000 d_real:0.003 d_cond:16206.768 d_fake:-0.006 d_gp:7.343 
/content/drive/app/GANimation-master/drive/app/GANimation-master/drive/app/GANimation-master/models/ganimation.py:126: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  real_img = Variable(self._input_real_img, volatile=True)
/content/drive/app/GANimation-master/drive/app/GANimation-master/drive/app/GANimation-master/models/ganimation.py:127: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  real_cond = Variable(self._input_real_cond, volatile=True)
/content/drive/app/GANimation-master/drive/app/GANimation-master/drive/app/GANimation-master/models/ganimation.py:128: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  desired_cond = Variable(self._input_desired_cond, volatile=True)
[23/10/2018 08:09:31] (V, epoch: 1, time_to_val: 26s) g_fake:0.000 g_cond:0.000 g_mskd_fake:-0.005 g_mskd_cond:15530.584 g_cyc:3.774 g_rgb:0.000 g_rgb_un:0.000 g_rgb_s:0.000 g_m1:0.056 g_m2:0.056 g_m1_s:0.724 g_m2_s:0.712 g_idt:0.000 d_real:0.003 d_cond:16206.768 d_fake:-0.006 d_gp:7.343 
saving the latest model (epoch 1, total_steps 25)
saved net: ./checkpoints/experiment_1/net_epoch_1_id_G.pth
saved net: ./checkpoints/experiment_1/net_epoch_1_id_D.pth
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    Train()
  File "train.py", line 27, in __init__
    self._train()
  File "train.py", line 40, in _train
    self._train_epoch(i_epoch)
  File "train.py", line 59, in _train_epoch
    for i_train_batch, train_batch in enumerate(self._dataset_train):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 184, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 184, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 173, in default_collate
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
RuntimeError: cannot unsqueeze empty tensor

**Comment by albertpumarola** [comment]
This issue was addressed in #52.
