### ISSUE TITLE
Loading specific epoch model failed

### ISSUE THREAD

**Issue by jas0n1ee** [albertpumarola/GANimation#56]
https://github.com/albertpumarola/GANimation/blob/faad9f9661ae56679d8b8491eab1f8ba20287f95/options/base_options.py#L73
In this line when checking with the filename, it should be the third(which is `file.split('_')[2]`) that stands for the epoch number.

**Comment by Blade6570** [comment]
just change to : found = int(file.split('_')[2]) == self._opt.load_epoch

**Comment by albertpumarola** [comment]
Solved
