### ISSUE TITLE
Are yg and Iyg mapping?

### ISSUE THREAD

**Issue by tjusxh** [albertpumarola/GANimation#57]
Thanks for your achievement. I have a doubt. Are the yg and Iyg pair in training? If not, that's so amazing. The structure can learn the mapping function. If yes, EmotioNet dataset have only 5 idensity. How to train ?

**Comment by albertpumarola** [comment]
Yes, pairs yg and Iyg are assumed. I do not understand what do you mean with 

> EmotioNet dataset have only 5 **idensity**

**Comment by albertpumarola** [comment]
Closed for inactivity
