### ISSUE TITLE
Segfault during model training and bad results

### ISSUE THREAD

**Issue by Morpheus3000** [albertpumarola/GANimation#58]
I tried running the training on about 110k images. I used all the default parameters for the training. But after around 11 epochs, I get a segfault in the training. I don't know where this error is originating from.

Also, since I had 11 epochs already saved, I just tried running a test on the sample images provided to see the performance. But the results seems very bad. Did you notice something similar? Is it because of the epoch that I used and it can be resolved with using a higher epoch?

Along the same lines, what would you say as the optimum epoch for the training? The default is about 30 epochs.

![n_0000000437_00540 jpg_out](https://user-images.githubusercontent.com/16116047/47508396-59d90180-d874-11e8-8c2b-3ff69de78128.png)

Thank you for your time.

**Comment by ryanzhng** [comment]
> I tried running the training on about 110k images. I used all the default parameters for the training. But after around 11 epochs, I get a segfault in the training. I don't know where this error is originating from.
> 
> Also, since I had 11 epochs already saved, I just tried running a test on the sample images provided to see the performance. But the results seems very bad. Did you notice something similar? Is it because of the epoch that I used and it can be resolved with using a higher epoch?
> 
> Along the same lines, what would you say as the optimum epoch for the training? The default is about 30 epochs.
> 
> ![n_0000000437_00540 jpg_out](https://user-images.githubusercontent.com/16116047/47508396-59d90180-d874-11e8-8c2b-3ff69de78128.png)
> 
> Thank you for your time.
Hello, I have a problem. 
what dataset did you use?
Thanks.

**Comment by ryanzhng** [comment]
> I tried running the training on about 110k images. I used all the default parameters for the training. But after around 11 epochs, I get a segfault in the training. I don't know where this error is originating from.
> 
> Also, since I had 11 epochs already saved, I just tried running a test on the sample images provided to see the performance. But the results seems very bad. Did you notice something similar? Is it because of the epoch that I used and it can be resolved with using a higher epoch?
> 
> Along the same lines, what would you say as the optimum epoch for the training? The default is about 30 epochs.
> 
> ![n_0000000437_00540 jpg_out](https://user-images.githubusercontent.com/16116047/47508396-59d90180-d874-11e8-8c2b-3ff69de78128.png)
> 
> Thank you for your time.

Hello, I am wondering what dataset did you use. 
Thanks.

**Comment by Morpheus3000** [comment]
> 
> 
> > I tried running the training on about 110k images. I used all the default parameters for the training. But after around 11 epochs, I get a segfault in the training. I don't know where this error is originating from.
> > Also, since I had 11 epochs already saved, I just tried running a test on the sample images provided to see the performance. But the results seems very bad. Did you notice something similar? Is it because of the epoch that I used and it can be resolved with using a higher epoch?
> > Along the same lines, what would you say as the optimum epoch for the training? The default is about 30 epochs.
> > ![n_0000000437_00540 jpg_out](https://user-images.githubusercontent.com/16116047/47508396-59d90180-d874-11e8-8c2b-3ff69de78128.png)
> > Thank you for your time.
> 
> Hello, I am wondering what dataset did you use.
> Thanks.

I used the same dataset as mentioned in the paper, the EmotioNet dataset.

**Comment by zhnyuren** [comment]
> > > I tried running the training on about 110k images. I used all the default parameters for the training. But after around 11 epochs, I get a segfault in the training. I don't know where this error is originating from.
> > > Also, since I had 11 epochs already saved, I just tried running a test on the sample images provided to see the performance. But the results seems very bad. Did you notice something similar? Is it because of the epoch that I used and it can be resolved with using a higher epoch?
> > > Along the same lines, what would you say as the optimum epoch for the training? The default is about 30 epochs.
> > > ![n_0000000437_00540 jpg_out](https://user-images.githubusercontent.com/16116047/47508396-59d90180-d874-11e8-8c2b-3ff69de78128.png)
> > > Thank you for your time.
> > 
> > 
> > Hello, I am wondering what dataset did you use.
> > Thanks.
> 
> I used the same dataset as mentioned in the paper, the EmotioNet dataset.

thanks.

**Comment by albertpumarola** [comment]
Hi, it is hard to know what is happening to you... Make sure that all the launch process is correct and the dataset is properly preprocessed.

**Comment by ZHANG-SHI-CHANG** [comment]
> 
> 
> I tried running the training on about 110k images. I used all the default parameters for the training. But after around 11 epochs, I get a segfault in the training. I don't know where this error is originating from.
> 
> Also, since I had 11 epochs already saved, I just tried running a test on the sample images provided to see the performance. But the results seems very bad. Did you notice something similar? Is it because of the epoch that I used and it can be resolved with using a higher epoch?
> 
> Along the same lines, what would you say as the optimum epoch for the training? The default is about 30 epochs.
> 
> ![n_0000000437_00540 jpg_out](https://user-images.githubusercontent.com/16116047/47508396-59d90180-d874-11e8-8c2b-3ff69de78128.png)
> 
> Thank you for your time.

Hi, can you share the dataset with me? My application for the data set failed...my email is 18354226160@163.com, thank you very much^_^

**Comment by EricGzq** [comment]
> > I tried running the training on about 110k images. I used all the default parameters for the training. But after around 11 epochs, I get a segfault in the training. I don't know where this error is originating from.
> > Also, since I had 11 epochs already saved, I just tried running a test on the sample images provided to see the performance. But the results seems very bad. Did you notice something similar? Is it because of the epoch that I used and it can be resolved with using a higher epoch?
> > Along the same lines, what would you say as the optimum epoch for the training? The default is about 30 epochs.
> > ![n_0000000437_00540 jpg_out](https://user-images.githubusercontent.com/16116047/47508396-59d90180-d874-11e8-8c2b-3ff69de78128.png)
> > Thank you for your time.
> 
> Hi, can you share the dataset with me? My application for the data set failed...my email is [18354226160@163.com](mailto:18354226160@163.com), thank you very much^_^

Hi! Did you get this dataset? I also need one, thank you very much. My email is [gzq_mail@163.com](mailto:gzq_mail@163.com)

**Comment by albertpumarola** [comment]
Closed for inactivity of the question. New posts are only asking for the dataset without the EmotioNet author's permission.
