### ISSUE TITLE
PatchGAN

### ISSUE THREAD

**Issue by xyy-ict** [albertpumarola/GANimation#60]
According to the paper and code comment, the network of discriminator here is a PatchGAN discriminator. However, the  implementation here is different from what is mentioned there [Question: PatchGAN Discriminator #39](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/39) for:

1) respective field of it is large enough to look the whole image

So, is the discriminator here still a PatchGAN discriminator? Why?

**Comment by albertpumarola** [comment]
Still is a PatchGan as it predicts an NxN array, where each position ij signifies whether the patch ij in the image is real or fake.
