### ISSUE TITLE
unsupervised strategy

### ISSUE THREAD

**Issue by chj1933** [albertpumarola/GANimation#61]
@albertpumarola ,老师，你好！请问你文中哪里体现你是无监督训练？

**Comment by albertpumarola** [comment]
I do not understand Chinese, but based on the google translation you are asking "Where do you express your unsupervised training?". You can find it in the [paper](https://arxiv.org/abs/1807.09251), equation 5. In the code it is implemented in models/ganimation.py

**Comment by chj1933** [comment]
@albertpumarola , I am so sorry, I want to say is where is unsupervised? How is it reflected?
