### ISSUE TITLE
Desired expression (action unit) for test

### ISSUE THREAD

**Issue by reese0629** [albertpumarola/GANimation#66]
Hi, thanks for the amazing work.
I have a question about expression (action unit) in test.py

In test.py, the desired expression is randomly generated from 0 to 1:
`expression = np.random.uniform(0, 1, opt.cond_nc)`

However, before network forward, the desired expression is divided by 5:
`expresion = torch.unsqueeze(torch.from_numpy(expresion/5.0), 0)`

If your intention is to normalize the desired expression to [0, 1],
then I think the desired expression should be generated from 0 to 5 in the first place, like this:
`expression = np.random.uniform(0, 5, opt.cond_nc)`

Please correct me if I am wrong.
Thank you!

**Comment by albertpumarola** [comment]
Yes, you are totally right sry,  the test code I uploaded was just as an example. For the paper, I used expressions extracted from the test set, that way I know the expression is humanly possible.
