### ISSUE TITLE
About the bad result.

### ISSUE THREAD

**Issue by Sam1224** [albertpumarola/GANimation#67]
![image](https://user-images.githubusercontent.com/33482912/48977445-2dafdb00-f0d5-11e8-8e75-94806e952ed6.png)
I use the CelebA dataset, and didn't change any parameter, after 30 epochs, the testing result appears like this. What's wrong?

**Comment by albertpumarola** [comment]
Its hard to know what's wrong without further information. Check that it is properly reading all your dataset samples. For your current results, it is basically not training.

**Comment by Sam1224** [comment]
> Its hard to know what's wrong without further information. Check that it is properly reading all your dataset samples. Based on your current results, it is basically not training.

Ok, I checked the .csv files just now, and found that my extraction results were strange, there were so many "0", so confused. The following image is the extraction result of the former image. My os is win10.
![image](https://user-images.githubusercontent.com/33482912/48986945-5d9ec300-f155-11e8-9e9b-f3cd758f5208.png)

**Comment by Sam1224** [comment]
> Its hard to know what's wrong without further information. Check that it is properly reading all your dataset samples. Based on your current results, it is basically not training.

Thanks a lot, i will check the dataset first.

**Comment by Sam1224** [comment]
@albertpumarola in my training process, these variables about G appeared to be 0 from the beginning, so confused.
![image](https://user-images.githubusercontent.com/33482912/49008566-180be580-f1a9-11e8-84b1-ff7d066f60e6.png)

**Comment by joyyang1997** [comment]
Hello， I use the CelebA as dataset too and I meet the same problem as you.
Have you find the solution?

**Comment by Bohn22** [comment]
> ![image](https://user-images.githubusercontent.com/33482912/48977445-2dafdb00-f0d5-11e8-8e75-94806e952ed6.png)
> I use the CelebA dataset, and didn't change any parameter, after 30 epochs, the testing result appears like this. What's wrong?

我也是用使用的CelebA dataset，得到的结果和您也类似，请问您最后解决了么？

**Comment by Bohn22** [comment]
> Hello， I use the CelebA as dataset too and I meet the same problem as you.
> Have you find the solution?

请问您最后解决了么？
