### ISSUE TITLE
PatchGAN question (compared to CycleGAN)

### ISSUE THREAD

**Issue by reese0629** [albertpumarola/GANimation#70]
Hello, I have a question about Patch GAN.

In the paper and codes, you mentioned that Patch GAN is used in Discriminator.
In the code below:
[https://github.com/albertpumarola/GANimation/blob/0acf388da5c0b47af00f49d978aa2fdba4b87cf9/networks/discriminator_wasserstein_gan.py#L5](url)
There are 6 layers before final output layer(Real/Fake and AU predictions), and the default training image data size is 128x128.
Based on my calculation, the 6th layer's feature map size is 2x2 (please correct me if I am wrong).
So I don't understand why you called it PatchGAN. (It seems like a normal conv net)

In contrast, the discriminator in CycleGAN has 3 layers with stride=2 and 2 layers with stride=1.
With default training image size(256x256), I calculated the final layer's feature map size is 30x30.

In CycleGAN, there are also detailed computations of receptive field size posted in Github:
[https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/39](url)
[https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/162](url)
Could you please post a computation of the receptive field size of the Discriminator in GANimation?

Thank you!!

**Comment by reese0629** [comment]
Additionally, I calculated receptive field of the discriminator in GANimation, based on the following links:
[https://fomoro.com/tools/receptive-fields/](url)
[https://medium.com/mlreview/a-guide-to-receptive-field-arithmetic-for-convolutional-neural-networks-e0f514068807](url)
The receptive field size is as follow:
layer 1 : 4
layer 2 : 10
layer 3 : 22
layer 4 : 46
layer 5 : 94
layer 6 : 190
layer 7 : 318

The two links above give the exact same results.
Is this computation wrong?
Do you have your own way to compute the receptive field?
Thank you.

**Comment by albertpumarola** [comment]
Yes 4x4, but still, it is looking at patches(16), it is not providing a single scalar for a given sample.
