### ISSUE TITLE
tensorboard images are unseen and test results are  so bad

### ISSUE THREAD

**Issue by HuayueZhang** [albertpumarola/GANimation#77]
This is what my tensorboard shows:
during debug,  I use "I = torch.from_numpy(image_numpy).permute(2, 0, 1)
            self._writer.add_image(sum_name, I / 255, it)" in place of
            "self._writer.add_image(sum_name, image_numpy, it)"
![image](https://user-images.githubusercontent.com/34264554/50556853-5ef57980-0d19-11e9-9784-6b492d4bfe2c.png)
These are my test results:
![000028 jpg_out](https://user-images.githubusercontent.com/34264554/50556845-484f2280-0d19-11e9-8cf7-44b0c3841e6d.png)
![000034 jpg_out](https://user-images.githubusercontent.com/34264554/50556846-4be2a980-0d19-11e9-9da6-80049208a44a.png)

**Comment by albertpumarola** [comment]
Clearly none of both behaivours is expected. You should not modify the I provided in order to replicate my results. Also, make sure that you have a rich dataset with correct expression labels for a proper training.
