### ISSUE TITLE
EmotionNet dataset

### ISSUE THREAD

**Issue by wanshun123** [albertpumarola/GANimation#78]
Is there a current download link for EmotionNet or a link to request access? I've only found https://github.com/SaraSherinThomas/Emotionet which points to https://www.pitt.edu/~emotion/downloads.html where EmotionNet isn't listed.

**Comment by wanshun123** [comment]
At https://cbcsl.ece.ohio-state.edu/downloads.html

**Comment by c1a1o1** [comment]
How long does it take to apply for EmotionNet data set?

**Comment by jiashu-zhu** [comment]
Hi c1a1o1, have you known how long does it take to apply for EmotionNet dataset? @c1a1o1
