### ISSUE TITLE
Error for test 

### ISSUE THREAD

**Issue by siyiding1216** [albertpumarola/GANimation#8]
Got below error. Dlibs api seems incompatiable...
~/GANimation$ python test.py --input_path  sample_dataset/imgs/
------------ Options -------------
aus_file: aus_openface.pkl
batch_size: 4
checkpoints_dir: ./checkpoints
cond_nc: 17
data_dir: None
dataset_mode: aus
do_saturate_mask: False
gpu_ids: [0]
image_size: 128
images_folder: imgs
input_path: sample_dataset/imgs/
is_train: False
load_epoch: 0
model: ganimation
n_threads_test: 1
name: experiment_1
output_dir: ./output
serial_batches: False
test_ids_file: test_ids.csv
train_ids_file: train_ids.csv
-------------- End ----------------
./checkpoints/experiment_1
Network generator_wasserstein_gan was created
Network discriminator_wasserstein_gan was created
NOT!! loaded net: ./checkpoints/experiment_1/net_epoch_0_id_G.pth
Model GANimation was created
Traceback (most recent call last):
  File "test.py", line 74, in <module>
    main()
  File "test.py", line 69, in main
    morph.morph_file(image_path, expression)
  File "test.py", line 28, in morph_file
    morphed_img = self._img_morph(img, expresion)
  File "test.py", line 33, in _img_morph
    bbs = face_recognition.face_locations(img)
  File "/home/ubuntu/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/face_recognition/api.py", line 118, in face_locations
    return [_trim_css_to_bounds(_rect_to_css(face), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, model)]
  File "/home/ubuntu/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/face_recognition/api.py", line 102, in _raw_face_locations
    return face_detector(img, number_of_times_to_upsample)
TypeError: __call__(): incompatible function arguments. The following argument types are supported:
    1. (self: dlib.fhog_object_detector, image: array, upsample_num_times: int=0L) -> dlib.rectangles

Invoked with: <dlib.fhog_object_detector object at 0x7f52b0efba40>, None, 1

**Comment by siyiding1216** [comment]
Do you have a specified version for dlib? I did have dlib installed and could do import dlib.

**Comment by naughtybabyfirst** [comment]
It just reads the path of folder in function morph_file(img_path),   instead of the path of the img.

**Comment by LinglanZhao** [comment]
The same error is reported to me. Have you solve this problem yet? @siyiding1216
