### ISSUE TITLE
RuntimeError : the size of tensor a (248) must match the size of tensor b (250) at non-singleton dimension 3 

### ISSUE THREAD

**Issue by songyoungeun** [albertpumarola/GANimation#88]
![image](https://user-images.githubusercontent.com/32218545/52705786-1e02ad00-2fc7-11e9-88bd-c9f5a19f557e.png)

l want to solution this error.
Please help me!!!!!

**Comment by octaviawfx** [comment]
> ![image](https://user-images.githubusercontent.com/32218545/52705786-1e02ad00-2fc7-11e9-88bd-c9f5a19f557e.png)
> 
> l want to solution this error.
> Please help me!!!!!

Have you solved this problem? it happend to me too, I guess it's caused by input images, it should be croped and the size should be like 128*128

**Comment by songyoungeun** [comment]
@octaviawfx  Oh Thanx!!!:)
